-- 코드를 입력하세요
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE M, REST_REVIEW R
WHERE M.MEMBER_ID = R.MEMBER_ID
AND M.MEMBER_ID IN (SELECT MEMBER_ID 
                      FROM REST_REVIEW 
                      GROUP BY MEMBER_ID
                      HAVING COUNT(MEMBER_ID) = (SELECT MAX(COUNT(MEMBER_ID)) 
                                                 FROM REST_REVIEW 
                                                 GROUP BY MEMBER_ID))
GROUP BY M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC
;