-- 코드를 작성해주세요

select CASE WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN '3Q'
            WHEN MONTH(DIFFERENTIATION_DATE) <= 12 THEN '4Q'
       END AS QUARTER
       , COUNT(*) AS ECOLI_COUNT
from ECOLI_DATA
group by QUARTER
order by QUARTER ASC
;