-- 코드를 입력하세요
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 
       TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID                       -- 조인조건
AND TO_CHAR(A.CREATED_DATE, 'YYYY-MM') = '2022-10'  -- 2022년 10월에 작성된 게시글
ORDER BY CREATED_DATE ASC, A.TITLE ASC              -- 댓글 작성일 오름차순 정렬, 게시글 제목 오름차순 정렬
;