SELECT DISTINCT(A.ID), B.FISH_NAME, A.LENGTH
FROM FISH_INFO A, FISH_NAME_INFO B, (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
                                     FROM FISH_INFO
                                     GROUP BY FISH_TYPE) C
WHERE A.FISH_TYPE = B.FISH_TYPE
AND A.LENGTH = C.MAX_LEN
AND A.FISH_TYPE = C.FISH_TYPE
ORDER BY A.ID