-- 코드를 입력하세요.
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TO_CHAR(DATE_OF_BIRTH, 'MM') = '03'   -- 생일이 03월
AND TLNO IS NOT NULL    -- 전화번호가 NULL이 아닌
AND GENDER = 'W'    -- 여성 회원이면서
ORDER BY MEMBER_ID ASC  -- 회원 ID 오름차순 정렬
;